package com.erimali.cntrygame;
//if starts with MIL -> Destroyable by army, boolean (?)
public enum Building{
    MIL_BASE,
    MIL_TRAINING_CAMP,
    FACTORY_PRODUCTION,
    MIL_FACTORY_PRODUCTION,
    MIL_FACTORY_GROUND_VEHICLES,
    MIL_FACTORY_WATER_VEHICLES,
    MIL_FACTORY_AIRCRAFT,
    MIL_NUCLEAR_FACILITY,
    AIRPORT,
    MIL_AIRPORT,
    RESEARCH_FACILITY,
    MIL_RESEARCH_FACILITY,
    MIL_INTELLIGENCE_AGENCY,


    ;
}
