package com.erimali.cntryrandom;

import javafx.geometry.Point2D;
import javafx.scene.paint.Color;

import java.util.LinkedList;
import java.util.List;

public abstract class GeoPolZone {
    // Generated randomly
    protected Point2D mainPoint;
    // Generated by Voronoi algorithms
    protected List<Point2D> boundary;
    // Generated by Perlin Noise
    protected double elevation;

    private static int ZONE_IDS = 0;
    private int zoneId = ZONE_IDS++;


    // For future game logic

    protected int provId;
    protected String name;
    protected List<GeoPolZone> neighbours = new LinkedList<>();


    public boolean aboveSeaLevel() {
        return elevation >= 0;
    }

    public abstract Color getColor();

    // Shoelace Formula for polygons
    public double area() {
        int n = boundary.size();
        if (n < 3) {
            return 0; // A polygon needs at least 3 points
        }

        double area = 0.0;
        for (int i = 0; i < n; i++) {
            Point2D p1 = boundary.get(i);
            Point2D p2 = boundary.get((i + 1) % n); // Wrap around to the first point
            area += (p1.getX() * p2.getY() - p2.getX() * p1.getY());
        }
        return Math.abs(area) / 2.0;
    }


    public String getName() {
        if (name == null) {
            return this instanceof RandProvince ? "Prov" : "Water" + provId;
        }
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getZoneId(){
        return zoneId;
    }

    public static void resetCountingIDS(){
        ZONE_IDS = 0;
        RandProvince.resetCountingIDS();
        RandWaterBody.resetCountingIDS();
    }

    public Point2D getMainPoint() {
        return mainPoint;
    }

    public void setMainPoint(Point2D mainPoint) {
        this.mainPoint = mainPoint;
    }

    public List<Point2D> getBoundary() {
        return boundary;
    }

    public void setBoundary(List<Point2D> boundary) {
        this.boundary = boundary;
    }

    public double getElevation() {
        return elevation;
    }

    public void setElevation(double elevation) {
        this.elevation = elevation;
    }

    public int getProvId() {
        return provId;
    }

    public void setProvId(int provId) {
        this.provId = provId;
    }


    public List<GeoPolZone> getNeighbours() {
        return neighbours;
    }

}
